package com.amity.socialcloud.uikit.common.config

// Generated by `apollo features sync` from apollo/features.json. Do not edit.

/**
 * UIKit modules a customer can switch off in config.json.
 * Naming the keys here rather than passing strings means a typo is a
 * compile error instead of a module that silently stays on — the failure
 * mode a flag exists to prevent.
 */
enum class AmityUIKitFeature(val key: String) {
    COMMUNITY("community"),
    CHAT("chat"),
    LIVE("live"),
    POLL("poll"),
    USER_RELATIONSHIP("userRelationship"),
    PUSH_NOTIFICATION("pushNotification"),
    POST("post"),
    STORY("story"),
    EVENTS("events"),
    FEED("feed"),
    COMMENT("comment"),
    REACTION("reaction"),
    PRODUCT("product"),
    ADS("ads"),
    DISCOVERY("discovery"),
}
