package com.amity.socialcloud.uikit.chat.compose.localization

import com.amity.socialcloud.uikit.chat.compose.R

object AmityChatStrings {

    fun buildStringKeyMap(): Map<String, Int> = mapOf(
        // Chat Home
        "chat.home.title" to R.string.amity_chat_home_title,
        "chat.tab.all" to R.string.amity_chat_tab_all,
        "chat.tab.direct" to R.string.amity_chat_tab_direct,
        "chat.tab.groups" to R.string.amity_chat_tab_groups,
        "chat.home.empty.title" to R.string.amity_chat_home_empty_title,
        "chat.home.empty.description" to R.string.amity_chat_home_empty_description,
        "chat.create.direct" to R.string.amity_chat_create_direct,
        "chat.create.group" to R.string.amity_chat_create_group,
        "chat.archived.navbar.title" to R.string.amity_chat_archived_navbar_title,
        "chat.archived" to R.string.amity_chat_archived,

        // Conversation
        "chat.unsupported.message" to R.string.amity_chat_unsupported_message,
        "chat.message.deleted" to R.string.amity_chat_message_deleted,
        "chat.load.error" to R.string.amity_chat_load_error,
        "chat.composer.placeholder" to R.string.amity_chat_composer_placeholder,
        "chat.replying.to" to R.string.amity_chat_replying_to,
        "chat.editing.message" to R.string.amity_chat_editing_message,
        "chat.message.replying.yourself" to R.string.amity_chat_message_replying_yourself,

        // Chat User Actions
        "chat.action.mute" to R.string.amity_chat_action_mute,
        "chat.action.mute.failed" to R.string.amity_chat_action_mute_failed,
        "chat.action.unmute" to R.string.amity_chat_action_unmute,
        "chat.action.unmute.failed" to R.string.amity_chat_action_unmute_failed,
        "chat.action.report.user" to R.string.amity_chat_action_report_user,
        "chat.action.unreport.user" to R.string.amity_chat_action_unreport_user,
        "chat.action.block.user" to R.string.amity_chat_action_block_user,
        "chat.action.unblock.user" to R.string.amity_chat_action_unblock_user,
        "chat.action.turn.off.notification" to R.string.amity_chat_action_turn_off_notification,
        "chat.action.turn.on.notification" to R.string.amity_chat_action_turn_on_notification,
        "chat.blocked.message" to R.string.amity_chat_blocked_message,
        "chat.block.confirm.title" to R.string.amity_chat_block_confirm_title,
        "chat.block.confirm.label" to R.string.amity_chat_block_confirm_label,
        "chat.block.confirm.message" to R.string.amity_chat_block_confirm_message,
        "chat.unblock.confirm.title" to R.string.amity_chat_unblock_confirm_title,
        "chat.unblock.confirm.message" to R.string.amity_chat_unblock_confirm_message,
        "chat.unblock.confirm.label" to R.string.amity_chat_unblock_confirm_label,
        "chat.block.success" to R.string.amity_chat_block_success,
        "chat.unblock.success" to R.string.amity_chat_unblock_success,
        "chat.block.failed" to R.string.amity_chat_block_failed,
        "chat.unblock.failed" to R.string.amity_chat_unblock_failed,
        "chat.group.edit.profile" to R.string.amity_chat_group_edit_profile,
        // Message Options
        "chat.option.reply" to R.string.amity_chat_option_reply,
        "chat.option.copy" to R.string.amity_chat_option_copy,
        "chat.option.edit" to R.string.amity_chat_option_edit,
        "chat.option.delete" to R.string.amity_chat_option_delete,
        "chat.option.report" to R.string.amity_chat_option_report,
        "chat.option.unreport" to R.string.amity_chat_option_unreport,
        "chat.action.save" to R.string.amity_chat_action_save,
        "chat.member.action.unreport" to R.string.amity_chat_member_action_unreport,

        // Failed / status messages
        "chat.message.not.sent" to R.string.amity_chat_message_not_sent,
        "chat.message.resend" to R.string.amity_chat_message_resend,
        "chat.message.failed.to.send" to R.string.amity_chat_message_failed_to_send,
        "chat.cancel" to R.string.amity_chat_cancel,
        "chat.char.limit.alert.title" to R.string.amity_chat_char_limit_alert_title,
        "chat.char.limit.alert.message" to R.string.amity_chat_char_limit_alert_message,
        // Group chat
        "chat.group.member.count" to R.string.amity_chat_group_member_count,
        "chat.waiting.for.network" to R.string.amity_chat_waiting_for_network,
        "chat.group.user.muted" to R.string.amity_chat_group_user_muted,
        "chat.group.user.banned" to R.string.amity_chat_group_user_banned,
        "chat.error.banned.chat.navbar.title" to R.string.amity_chat_error_banned_chat_navbar_title,

        // Create chat
        "chat.create.conversation.title" to R.string.amity_chat_create_conversation_title,
        "chat.no.users.found" to R.string.amity_chat_no_users_found,
        "chat.select.members.title" to R.string.amity_chat_select_members_title,
        "chat.next" to R.string.amity_chat_next,
        "chat.create.group.title" to R.string.amity_chat_create_group_title,
        "chat.group.name.label" to R.string.amity_chat_group_name_label,
        "chat.group.name.placeholder" to R.string.amity_chat_group_name_placeholder,
        "chat.group.members.label" to R.string.amity_chat_group_members_label,
        "chat.create.group.button" to R.string.amity_chat_create_group_button,
        "chat.create.group.error" to R.string.amity_chat_create_group_error,
        "chat.create.group.success" to R.string.amity_chat_create_group_success,

        // Group settings
        "chat.group.settings.section" to R.string.amity_chat_group_settings_section,
        "chat.group.notifications" to R.string.amity_chat_group_notifications,
        "chat.your.preferences.section" to R.string.amity_chat_your_preferences_section,
        "chat.edit.group.profile.navbar.title" to R.string.amity_chat_edit_group_profile_navbar_title,
        "chat.group.members" to R.string.amity_chat_group_members,
        "chat.group.leave" to R.string.amity_chat_group_leave,
        "chat.group.leave.confirm.title" to R.string.amity_chat_group_leave_confirm_title,
        "chat.group.leave.confirm.message" to R.string.amity_chat_group_leave_confirm_message,
        "chat.group.leave.confirm.label" to R.string.amity_chat_group_leave_confirm_label,
        "chat.group.leave.last.mod.title" to R.string.amity_chat_group_leave_last_mod_title,
        "chat.group.leave.last.mod.message" to R.string.amity_chat_group_leave_last_mod_message,
        "chat.group.promote.member" to R.string.amity_chat_group_promote_member,
        "chat.group.save" to R.string.amity_chat_group_save,
        "chat.group.edit.notification.save" to R.string.amity_chat_group_edit_notification_save,
        "chat.group.edit.permission.save" to R.string.amity_chat_group_edit_permission_save,
        "chat.group.edit.profile.save" to R.string.amity_chat_group_edit_profile_save,
        "chat.group.edit.profile.failed" to R.string.amity_chat_group_edit_profile_failed,
        "chat.group.profile" to R.string.amity_chat_group_profile,
        "chat.group.name.required" to R.string.amity_chat_group_name_required,
        "chat.group.name.optional" to R.string.amity_chat_group_name_optional,
        "chat.privacy.label" to R.string.amity_chat_privacy_label,
        "chat.create.group.public.title" to R.string.amity_chat_create_group_public_title,
        "chat.create.group.public.subtitle" to R.string.amity_chat_create_group_public_subtitle,
        "chat.create.group.private.title" to R.string.amity_chat_create_group_private_title,
        "chat.create.group.private.subtitle" to R.string.amity_chat_create_group_private_subtitle,
        "chat.edit.group.profile.name.placeholder" to R.string.amity_chat_edit_group_profile_name_placeholder,
        // Member List
        "chat.member.list.title" to R.string.amity_chat_member_list_title,
        "chat.group.member.list.tab.title" to R.string.amity_chat_group_member_list_tab_title,
        "chat.member.tab.moderators" to R.string.amity_chat_member_tab_moderators,
        "chat.member.action.promote" to R.string.amity_chat_member_action_promote,
        "chat.member.action.demote" to R.string.amity_chat_member_action_demote,
        "chat.member.action.remove" to R.string.amity_chat_member_action_remove,
        "chat.user.action.ban" to R.string.amity_chat_user_action_ban,
        "chat.mute.confirm.label" to R.string.amity_chat_mute_confirm_label,
        "chat.unmute.confirm.label" to R.string.amity_chat_unmute_confirm_label,
        "chat.member.you.suffix" to R.string.amity_chat_member_you_suffix,
        "chat.member.you" to R.string.amity_chat_member_you,
        "chat.add.member.title" to R.string.amity_chat_add_member_title,
        "chat.add.member.button" to R.string.amity_chat_add_member_button,
        "chat.add.member.chip" to R.string.amity_chat_add_member_chip,

        // Search
        "chat.search.placeholder" to R.string.amity_chat_search_placeholder,
        "chat.search.min.chars" to R.string.amity_chat_search_min_chars,
        "chat.search.no.results" to R.string.amity_chat_search_no_results,
        "chat.search.tab.chats" to R.string.amity_chat_search_tab_chats,
        "chat.search.tab.messages" to R.string.amity_chat_search_tab_messages,

        // Message Report
        "chat.report.title" to R.string.amity_chat_report_title,
        "chat.report.description" to R.string.amity_chat_report_description,
        "chat.report.submit" to R.string.amity_chat_report_submit,
        "chat.toast.message.reported" to R.string.amity_chat_toast_message_reported,
        "chat.toast.un.report.message" to R.string.amity_chat_toast_un_report_message,
        "chat.label.loading.chat" to R.string.amity_chat_label_loading_chat,
        "chat.report.others" to R.string.amity_chat_report_others,
        "chat.report.other.reason.desc" to R.string.amity_chat_report_other_reason_desc,
        "chat.report.other.reason.optional" to R.string.amity_chat_report_other_reason_optional,
        "chat.report.other.reason.placeholder" to R.string.amity_chat_report_other_reason_placeholder,

        // Notification Preferences
        "chat.group.notif.pref.navbar.title" to R.string.amity_chat_group_notif_pref_navbar_title,
        "chat.notifications.title" to R.string.amity_chat_notifications_title,
        "chat.notifications.on" to R.string.amity_chat_notifications_on,
        "chat.notifications.off" to R.string.amity_chat_notifications_off,
        "chat.group.notification.preference.description" to R.string.amity_chat_group_notification_preference_description,
        "chat.group.notifications.disabled" to R.string.amity_chat_group_notifications_disabled,
        "chat.notifications.disabled" to R.string.amity_chat_notifications_disabled,

        // Notification Modes
        "chat.group.notification.default.label" to R.string.amity_chat_group_notification_default_label,
        "chat.group.notification.default.title" to R.string.amity_chat_group_notification_default_title,
        "chat.group.notification.default.desc" to R.string.amity_chat_group_notification_default_desc,
        "chat.group.notification.subscribe.label" to R.string.amity_chat_group_notification_subscribe_label,
        "chat.group.notification.subscribe.title" to R.string.amity_chat_group_notification_subscribe_title,
        "chat.group.notification.subscribe.desc" to R.string.amity_chat_group_notification_subscribe_desc,
        "chat.group.notification.silent.label" to R.string.amity_chat_group_notification_silent_label,
        "chat.group.notification.silent.title" to R.string.amity_chat_group_notification_silent_title,
        "chat.group.notification.silent.desc" to R.string.amity_chat_group_notification_silent_desc,

        // Media Composer
        "chat.media.camera" to R.string.amity_chat_media_camera,
        "chat.media.photo" to R.string.amity_chat_media_photo,
        "chat.reply.photo.label" to R.string.amity_chat_reply_photo_label,
        "chat.reply.video.label" to R.string.amity_chat_reply_video_label,

        // Member Actions (extended)
        "chat.option.report" to R.string.amity_chat_option_report,
        "chat.mute.confirm.title" to R.string.amity_chat_mute_confirm_title,
        "chat.mute.confirm.message" to R.string.amity_chat_mute_confirm_message,
        "chat.unmute.confirm.title" to R.string.amity_chat_unmute_confirm_title,
        "chat.unmute.confirm.message" to R.string.amity_chat_unmute_confirm_message,
        "chat.ban.confirm.title" to R.string.amity_chat_ban_confirm_title,
        "chat.ban.confirm.message" to R.string.amity_chat_ban_confirm_message,
        "chat.ban.confirm.label" to R.string.amity_chat_ban_confirm_label,
        "chat.unban.confirm.title" to R.string.amity_chat_unban_confirm_title,
        "chat.unban.confirm.message" to R.string.amity_chat_unban_confirm_message,
        "chat.unban.confirm.label" to R.string.amity_chat_unban_confirm_label,

        // Banned Members Page
        "chat.banned.member.list.navbar.title" to R.string.amity_chat_banned_member_list_navbar_title,
        "chat.banned.members.empty" to R.string.amity_chat_banned_members_empty,
        "chat.member.action.unban" to R.string.amity_chat_member_action_unban,

        // Message Preview
        "chat.preview.sent.photo" to R.string.amity_chat_preview_sent_photo,
        "chat.preview.sent.video" to R.string.amity_chat_preview_sent_video,
        "chat.preview.deleted" to R.string.amity_chat_preview_deleted,
        "chat.preview.no.message" to R.string.amity_chat_preview_no_message,
        "chat.deleted.user" to R.string.amity_chat_deleted_user,
        "chat.archived.toast" to R.string.amity_chat_archived_toast,
        "chat.create.new.chat" to R.string.amity_chat_create_new_chat,

        // Archive / Unarchive
        "chat.archive" to R.string.amity_chat_archive,
        "chat.unarchive" to R.string.amity_chat_unarchive,
        "chat.unarchived.toast" to R.string.amity_chat_unarchived_toast,
        "chat.archive.error.toast" to R.string.amity_chat_archive_error_toast,
        "chat.unarchive.error.toast" to R.string.amity_chat_unarchive_error_toast,
        "chat.archive.limit.title" to R.string.amity_chat_archive_limit_title,
        "chat.archive.limit.message" to R.string.amity_chat_archive_limit_message,

        // Member Permissions
        "chat.group.member.permissions.navbar.title" to R.string.amity_chat_group_member_permissions_navbar_title,
        "chat.group.edit.permissions.messaging.title" to R.string.amity_chat_group_edit_permissions_messaging_title,
        "chat.group.edit.permissions.everyone.title" to R.string.amity_chat_group_edit_permissions_everyone_title,
        "chat.group.edit.permissions.everyone.description" to R.string.amity_chat_group_edit_permissions_everyone_description,
        "chat.group.edit.permissions.moderators.only.title" to R.string.amity_chat_group_edit_permissions_moderators_only_title,
        "chat.group.edit.permissions.moderators.only.description" to R.string.amity_chat_group_edit_permissions_moderators_only_description,
        "chat.group.permission.only.moderators.banner" to R.string.amity_chat_group_permission_only_moderators_banner,
        // Settings (extended)
        "chat.group.banned.members" to R.string.amity_chat_group_banned_members,
        "chat.group.member.permissions" to R.string.amity_chat_group_member_permissions,

        // Message Bubble
        "chat.see.more" to R.string.amity_chat_see_more,

        // Reply
        "chat.reply.you" to R.string.amity_chat_reply_you,
        "chat.reply.you.to.yourself" to R.string.amity_chat_reply_you_to_yourself,
        "chat.reply.to.you" to R.string.amity_chat_reply_to_you,
        "chat.reply.to.themself" to R.string.amity_chat_reply_to_themself,
        "chat.reply.you.to.deleted" to R.string.amity_chat_reply_you_to_deleted,
        "chat.reply.to.deleted" to R.string.amity_chat_reply_to_deleted,
        "chat.replied.message" to R.string.amity_chat_message_replied_message,

        // Status strings
        "chat.status.edited" to R.string.amity_chat_status_edited,
        "chat.sending.status" to R.string.amity_chat_sending_status,
        "chat.status.failed" to R.string.amity_chat_status_failed,
        "chat.preview.not.available" to R.string.amity_chat_preview_not_available,
        "chat.preview.message" to R.string.amity_chat_preview_message,
        "chat.bubble.link.preview.no.data" to R.string.amity_chat_bubble_link_preview_no_data,

        // Success / error snackbar strings
        "chat.action.report.user.success" to R.string.amity_chat_action_report_user_success,
        "chat.action.unreport.user.success" to R.string.amity_chat_action_unreport_user_success,
        "chat.action.report.user.failed" to R.string.amity_chat_action_report_user_failed,
        "chat.action.unreport.user.failed" to R.string.amity_chat_action_unreport_user_failed,
        "chat.error.update.notification" to R.string.amity_chat_group_notification_save_error,
        "chat.action.leave.group.failed" to R.string.amity_chat_action_leave_group_failed,
        "chat.toast.message.reported.error" to R.string.amity_chat_toast_message_reported_error,
        "chat.success.member.added" to R.string.amity_chat_success_member_added,
        "chat.add.group.member.toast.failed" to R.string.amity_chat_add_group_member_toast_failed,
        "chat.action.remove.member" to R.string.amity_chat_action_remove_member,
        "chat.action.remove.member.failed" to R.string.amity_chat_action_remove_member_failed,
        "chat.action.promote.member.failed" to R.string.amity_chat_action_promote_member_failed,
        "chat.action.demote.member.failed" to R.string.amity_chat_action_demote_member_failed,
        "chat.action.mute.user" to R.string.amity_chat_action_mute_user,
        "chat.action.mute.user.failed" to R.string.amity_chat_action_mute_user_failed,
        "chat.action.unmute.user" to R.string.amity_chat_action_unmute_user,
        "chat.action.unmute.user.failed" to R.string.amity_chat_action_unmute_user_failed,
        "chat.action.ban.member.failed" to R.string.amity_chat_action_ban_member_failed,
        "chat.action.unban.user" to R.string.amity_chat_action_unban_user,
        "chat.action.unban.user.failed" to R.string.amity_chat_action_unban_user_failed,
        "chat.privacy.warning" to R.string.amity_chat_privacy_warning,
        "chat.save.photo.success" to R.string.amity_chat_save_photo_success,
        "chat.save.photo.failed" to R.string.amity_chat_save_photo_failed,
        "chat.save.video.success" to R.string.amity_chat_save_video_success,
        "chat.save.video.failed" to R.string.amity_chat_save_video_failed,
        "chat.archived.empty.title" to R.string.amity_chat_archived_empty_title,
        "chat.archived.badge.label" to R.string.amity_chat_archived_badge_label,
        "chat.group.notification.save.success" to R.string.amity_chat_group_notification_save_success,
        "group.notification.save.error" to R.string.amity_group_notification_save_error,

        // Notification Preferences (extended)
        "chat.group.notification.preference.title" to R.string.amity_chat_group_notification_preference_title,

        // Member List toasts
        "chat.group.member.list.toast.banned" to R.string.amity_chat_group_member_list_toast_banned,
        "chat.group.member.list.toast.promoted" to R.string.amity_chat_group_member_list_toast_promoted,
        "chat.group.member.list.toast.demoted" to R.string.amity_chat_group_member_list_toast_demoted,

        // Message Actions
        "chat.mention.everyone" to R.string.amity_chat_mention_everyone,
        "chat.button.ok" to R.string.amity_chat_button_ok,
        "chat.toast.delete.error" to R.string.amity_chat_toast_delete_error,
        "chat.unknown.user" to R.string.amity_chat_unknown_user,
        "chat.label.banned.from.chat" to R.string.amity_chat_label_banned_from_chat,
        "chat.leave.without.finishing.title" to R.string.amity_chat_leave_without_finishing_title,
        "chat.leave.without.finishing.message" to R.string.amity_chat_leave_without_finishing_message,
        "chat.leave.without.finishing.label" to R.string.amity_chat_leave_without_finishing_label,
        "chat.member.limit.reached.title" to R.string.amity_chat_member_limit_reached_title,
        "chat.member.limit.reached.message" to R.string.amity_chat_member_limit_reached_message,

        "chat.group.member.list.demote.confirm" to R.string.amity_chat_group_member_list_demote_confirm,
        "chat.group.member.list.demote.message" to R.string.amity_chat_group_member_list_demote_message,
        "chat.group.member.list.demote.title" to R.string.amity_chat_group_member_list_demote_title,
        "chat.group.member.list.promote.confirm" to R.string.amity_chat_group_member_list_promote_confirm,
        "chat.group.member.list.promote.message" to R.string.amity_chat_group_member_list_promote_message,
        "chat.group.member.list.promote.title" to R.string.amity_chat_group_member_list_promote_title,
        "chat.group.member.list.remove.confirm" to R.string.amity_chat_group_member_list_remove_confirm,
        "chat.group.member.list.remove.message" to R.string.amity_chat_group_member_list_remove_message,
        "chat.group.member.list.remove.title" to R.string.amity_chat_group_member_list_remove_title,

        "chat.delete.alert.message" to R.string.amity_chat_delete_alert_message,
        "chat.delete.alert.title" to R.string.amity_chat_delete_alert_title,
        "chat.group.edit.permissions.everyone.description" to R.string.amity_chat_group_edit_permissions_everyone_description,
        "chat.group.member.action.mute" to R.string.amity_chat_group_member_action_mute,
        "chat.group.member.action.unmute" to R.string.amity_chat_group_member_action_unmute,
        "chat.reply.name.to.name" to R.string.amity_chat_reply_name_to_name,
        "chat.reply.name.to.themself" to R.string.amity_chat_reply_name_to_themself,
        "chat.reply.name.to.you" to R.string.amity_chat_reply_name_to_you,
        "chat.reply.you.to.name" to R.string.amity_chat_reply_you_to_name,
        "chat.timestamp.now" to R.string.amity_chat_timestamp_now,
        "chat.toast.member.added" to R.string.amity_chat_toast_member_added,
        "chat.toast.members.add.error" to R.string.amity_chat_toast_members_add_error,
        "chat.toast.members.added" to R.string.amity_chat_toast_members_added,
        "chat.toast.un.report.message.error" to R.string.amity_chat_toast_un_report_message_error,
        "chat.message.no.preview" to R.string.amity_chat_message_no_preview,
        "chat.no.members.found" to R.string.amity_chat_no_members_found,
        "chat.toast.delete.error" to R.string.amity_chat_toast_delete_error,

        // Miscellaneous
        "chat.error.banned.chat.title" to R.string.amity_chat_error_banned_chat_title,
        "chat.error.banned.chat.sub.title" to R.string.amity_chat_error_banned_chat_sub_title,
        "chat.home.menu.archived" to R.string.amity_chat_home_menu_archived,
        "chat.loading.label" to R.string.amity_chat_loading_label,
        "chat.reach.mention.limit.title" to R.string.amity_chat_reach_mention_limit_title,
        "chat.reach.mention.limit.message" to R.string.amity_chat_reach_mention_limit_message,
        "chat.toast.banned.word" to R.string.amity_chat_toast_banned_word,
        "chat.toast.copied" to R.string.amity_chat_toast_copied,
        "chat.toast.group.chat.left" to R.string.amity_chat_toast_group_chat_left,
        "chat.toast.link.not.allow" to R.string.amity_chat_toast_link_not_allow,
        "chat.user.is.muted" to R.string.amity_chat_user_is_muted,
        "chat.toast.reply.parent.deleted" to R.string.amity_chat_toast_reply_parent_deleted,
        "chat.edit.group.perm.toast.failed" to R.string.amity_chat_edit_group_perm_toast_failed,
        "chat.edit.group.perm.toast.success" to R.string.amity_chat_edit_group_perm_toast_success,
        "chat.reaction.label.like" to R.string.amity_chat_reaction_label_like,
        "chat.reaction.label.love" to R.string.amity_chat_reaction_label_love,
        "chat.reaction.label.fire" to R.string.amity_chat_reaction_label_fire,
        "chat.reaction.label.happy" to R.string.amity_chat_reaction_label_happy,
        "chat.reaction.label.sad" to R.string.amity_chat_reaction_label_sad,
        "chat.jump.to.message.unavailable" to R.string.amity_chat_jump_to_message_unavailable,
        "chat.report.error.title" to R.string.amity_chat_report_error_title,
        "chat.report.error.desc" to R.string.amity_chat_report_error_desc,
        "chat.report.error.close" to R.string.amity_chat_report_error_close,
    )
}
